//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gen {
  using System;
  
  
  /// <summary>
  ///   A strongly-typed resource class, for looking up localized strings, etc.
  /// </summary>
  // This class was auto-generated by the StronglyTypedResourceBuilder
  // class via a tool like ResGen or Visual Studio.
  // To add or remove a member, edit your .ResX file then rerun ResGen
  // with the /str option, or rebuild your VS project.
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  public class Messages {
    
    private static global::System.Resources.ResourceManager resourceMan;
    
    private static global::System.Globalization.CultureInfo resourceCulture;
    
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal Messages() {
    }
    
    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Resources.ResourceManager ResourceManager {
      get {
        if (object.ReferenceEquals(resourceMan, null)) {
          global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gen.Messages", typeof(Messages).Assembly);
          resourceMan = temp;
        }
        return resourceMan;
      }
    }
    
    /// <summary>
    ///   Overrides the current thread's CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Globalization.CultureInfo Culture {
      get {
        return resourceCulture;
      }
      set {
        resourceCulture = value;
      }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to &quot;[NO TABLE NAMED ‘{0}’ EXISTS]&quot;.
    /// </summary>
    public static string DatabaseCollection_ConvertInput_TableNotFound {
      get {
        return ResourceManager.GetString("DatabaseCollection ConvertInput TableNotFound", resourceCulture);
      }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Xml Database Configuration|*.xdata|Xml File|*.xml|Known Xml Data-Config|*.xml;*.xdata|All Files|*.
    /// </summary>
    public static string Filter_Database_Config {
      get {
        return ResourceManager.GetString("Filter Database Config", resourceCulture);
      }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to generator-config|*.generator-config;|All Files|*.
    /// </summary>
    public static string Filter_Generator_Config {
      get {
        return ResourceManager.GetString("Filter Generator Config", resourceCulture);
      }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Xml Template File|*.xtpl|Xml File|*.xml|All Files|*.
    /// </summary>
    public static string Filter_Xml_Template {
      get {
        return ResourceManager.GetString("Filter Xml Template", resourceCulture);
      }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to New Database {0:00#}.
    /// </summary>
    public static string Node_New_Database_Element {
      get {
        return ResourceManager.GetString("Node New Database Element", resourceCulture);
      }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to New Table Element {0:00#}.
    /// </summary>
    public static string Node_New_Table_Element {
      get {
        return ResourceManager.GetString("Node New Table Element", resourceCulture);
      }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The table ({0}) should contain a Primary Key..
    /// </summary>
    public static string TableElement_PrimaryKeyNotFound {
      get {
        return ResourceManager.GetString("TableElement PrimaryKeyNotFound", resourceCulture);
      }
    }
  }
}
