//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gen {
  using System;
  
  
  /// <summary>
  ///   A strongly-typed resource class, for looking up localized strings, etc.
  /// </summary>
  // This class was auto-generated by the StronglyTypedResourceBuilder
  // class via a tool like ResGen or Visual Studio.
  // To add or remove a member, edit your .ResX file then rerun ResGen
  // with the /str option, or rebuild your VS project.
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  internal class Strings {
    
    private static global::System.Resources.ResourceManager resourceMan;
    
    private static global::System.Globalization.CultureInfo resourceCulture;
    
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal Strings() {
    }
    
    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Resources.ResourceManager ResourceManager {
      get {
        if (object.ReferenceEquals(resourceMan, null)) {
          global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gen.Strings", typeof(Strings).Assembly);
          resourceMan = temp;
        }
        return resourceMan;
      }
    }
    
    /// <summary>
    ///   Overrides the current thread's CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Globalization.CultureInfo Culture {
      get {
        return resourceCulture;
      }
      set {
        resourceCulture = value;
      }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to AdapterNs;AdapterT;AdapterNsT;CommandNs;CommandT;CommandNsT;ConnectionT;ConnectionNsT;ConnectionNs;ReaderNs;ReaderT;ReaderNsT;ParameterT.
    /// </summary>
    internal static string Factory_AcAdapt {
      get {
        return ResourceManager.GetString("Factory_AcAdapt", resourceCulture);
      }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to DbType;FriendlyName.
    /// </summary>
    internal static string Factory_AcData {
      get {
        return ResourceManager.GetString("Factory_AcData", resourceCulture);
      }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Date;Time;DateTime.
    /// </summary>
    internal static string Factory_AcErratum {
      get {
        return ResourceManager.GetString("Factory_AcErratum", resourceCulture);
      }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to FieldValues;FieldValues,Cdf;FieldValuesNK;FieldValuesNK,Cdf;PKDataName;PKDataType;PKDataTypeNative;PKNativeNullType;PKNativeNullValue;PKDescription;PKDataNameC;PKCleanName;PKCleanName,Nodash;PKFriendlyName;PKFriendlyNameC.
    /// </summary>
    internal static string Factory_AcField {
      get {
        return ResourceManager.GetString("Factory_AcField", resourceCulture);
      }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to PKDataName;PKDataType;PKDataTypeNative;PKDescription.
    /// </summary>
    internal static string Factory_AcPkType {
      get {
        return ResourceManager.GetString("Factory_AcPkType", resourceCulture);
      }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to PK;pk;PrimaryKey;PrimaryKeyCleanC.
    /// </summary>
    internal static string Factory_AcPrime {
      get {
        return ResourceManager.GetString("Factory_AcPrime", resourceCulture);
      }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Table;TableName;tablename;TableNameC;TableNameClean;tablenameclean;TableNameCClean;TableCleanName;TableCleanNameC;TableType;tabletype.
    /// </summary>
    internal static string Factory_AcTable {
      get {
        return ResourceManager.GetString("Factory_AcTable", resourceCulture);
      }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to CleanName;FriendlyName;FriendlyNameC;DataType;datatype;DataTypeNative;datatypenative;FlashDataType;DataName;dataname;DataNameC;FormatString;FormType;ActionType;max;Max;LMAX;nmax;smax;MaxLength;IsString;IsBool;IsNum;Native;UseFormat;IsNullable;NativeNullType;NativeNullValue;DataTypeNullable;FieldIndex;Description;DefaultValue.
    /// </summary>
    internal static string Factory_AcTypes {
      get {
        return ResourceManager.GetString("Factory_AcTypes", resourceCulture);
      }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Xml Database Configuration|*.xdata|Xml File|*.xml|Known Xml Data-Config|*.xml;*.xdata|All Files|*.
    /// </summary>
    internal static string Filter_Database_Config {
      get {
        return ResourceManager.GetString("Filter Database Config", resourceCulture);
      }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to generator-config|*.generator-config;|All Files|*.
    /// </summary>
    internal static string Filter_Generator_Config {
      get {
        return ResourceManager.GetString("Filter Generator Config", resourceCulture);
      }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Xml Template File|*.xtpl|Xml File|*.xml|All Files|*.
    /// </summary>
    internal static string Filter_Xml_Template {
      get {
        return ResourceManager.GetString("Filter Xml Template", resourceCulture);
      }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to TemplateFactory.ConvertInput.
    /// </summary>
    internal static string LogFactoryConvert_Title {
      get {
        return ResourceManager.GetString("LogFactoryConvert_Title", resourceCulture);
      }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Table: “{0}”.
    /// </summary>
    internal static string LogTable_Format {
      get {
        return ResourceManager.GetString("LogTable_Format", resourceCulture);
      }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Tag: ‘{0}’ value..
    /// </summary>
    internal static string LogTemplateFactoryErr_Filter {
      get {
        return ResourceManager.GetString("LogTemplateFactoryErr_Filter", resourceCulture);
      }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to TemplateFactory.ConvertInput ERROR.
    /// </summary>
    internal static string LogTemplateFactoryErr_Title {
      get {
        return ResourceManager.GetString("LogTemplateFactoryErr_Title", resourceCulture);
      }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Match0.Value=“{0}”
    ///Match0.Name=“{1}”
    ///Match0.Params=“{2}”.
    /// </summary>
    internal static string LogTemplateInfo_Format {
      get {
        return ResourceManager.GetString("LogTemplateInfo_Format", resourceCulture);
      }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to TemplateFactory.
    /// </summary>
    internal static string LogTemplateInfo_Title {
      get {
        return ResourceManager.GetString("LogTemplateInfo_Title", resourceCulture);
      }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Error finding database or table for view..
    /// </summary>
    internal static string MsgDatabaseOrTableNullError_Exception {
      get {
        return ResourceManager.GetString("MsgDatabaseOrTableNullError_Exception", resourceCulture);
      }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Exiting generation....
    /// </summary>
    internal static string MsgDatabaseOrTableNullError_Message {
      get {
        return ResourceManager.GetString("MsgDatabaseOrTableNullError_Message", resourceCulture);
      }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Error finding database or table for view..
    /// </summary>
    internal static string MsgDatabaseOrTableNullError_Title {
      get {
        return ResourceManager.GetString("MsgDatabaseOrTableNullError_Title", resourceCulture);
      }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to \$\((set\w*|begin\w*|end\w*|print\w*|Table\w*|Field\w*)\:(?&lt;innerElement&gt;[^\)]+)\).
    /// </summary>
    internal static string Regex_Field_Template_Tag {
      get {
        return ResourceManager.GetString("Regex Field Template Tag", resourceCulture);
      }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to MSysAccessStorage,MSysAccessXML,MSysACEs,MSysCompactError,MSysIMEXColumns,MSysIMEXSpecs,MSysModules,MSysModules2,MSysNavPaneGroupCategories,MSysNavPaneGroups,MSysNavPaneGroupToObjects,MSysNavPaneObjectIDs,MSysObjects,MSysQueries,MSysRelationships.
    /// </summary>
    internal static string Schema_Access_Fields {
      get {
        return ResourceManager.GetString("Schema Access Fields", resourceCulture);
      }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Columns.
    /// </summary>
    internal static string Schema_Columns {
      get {
        return ResourceManager.GetString("Schema Columns", resourceCulture);
      }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to DataTypes.
    /// </summary>
    internal static string Schema_DataTypes {
      get {
        return ResourceManager.GetString("Schema DataTypes", resourceCulture);
      }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Indexes.
    /// </summary>
    internal static string Schema_Indexes {
      get {
        return ResourceManager.GetString("Schema Indexes", resourceCulture);
      }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Procedures.
    /// </summary>
    internal static string Schema_Procedures {
      get {
        return ResourceManager.GetString("Schema Procedures", resourceCulture);
      }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to ReservedWords.
    /// </summary>
    internal static string Schema_ReservedWords {
      get {
        return ResourceManager.GetString("Schema ReservedWords", resourceCulture);
      }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Restrictions.
    /// </summary>
    internal static string Schema_Restrictions {
      get {
        return ResourceManager.GetString("Schema Restrictions", resourceCulture);
      }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Tables.
    /// </summary>
    internal static string Schema_Tables {
      get {
        return ResourceManager.GetString("Schema Tables", resourceCulture);
      }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Views.
    /// </summary>
    internal static string Schema_Views {
      get {
        return ResourceManager.GetString("Schema Views", resourceCulture);
      }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;&gt;
    ///&lt;DatabaseCollection&gt;{inner-content}
    ///&lt;/DatabaseCollection&gt;
    ///.
    /// </summary>
    internal static string Tbl_DatabaseCollection {
      get {
        return ResourceManager.GetString("Tbl DatabaseCollection", resourceCulture);
      }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;&gt;
    ///&lt;Database&gt;{inner-content}
    ///&lt;/Database&gt;.
    /// </summary>
    internal static string Tbl_DatabaseElement {
      get {
        return ResourceManager.GetString("Tbl DatabaseElement", resourceCulture);
      }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to 
    ///		&lt;Field
    ///			DataName=&quot;%COLUMN_NAME%&quot;
    ///			NativeType=&quot;%NATIVE_TYPE%&quot;
    ///			DataType=&quot;%DATA_TYPE%&quot;
    ///			IsNullable=&quot;%IS_NULLABLE%&quot;
    ///			MaxLength=&quot;%CHARACTER_MAXIMUM_LENGTH%&quot;
    ///		/&gt;.
    /// </summary>
    internal static string Tbl_FieldElement {
      get {
        return ResourceManager.GetString("Tbl FieldElement", resourceCulture);
      }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to 
    ///	&lt;Table Name=&quot;%TABLE_NAME%&quot; PrimaryKey=&quot;%PKUNKNOWN%&quot;&gt;{inner-content}
    ///	&lt;/Table&gt;.
    /// </summary>
    internal static string Tbl_TableElement {
      get {
        return ResourceManager.GetString("Tbl TableElement", resourceCulture);
      }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to AutoIncr,Currency,DateTime,Memo,Number,Ole,Hyperlink,Text,YesNo.
    /// </summary>
    internal static string TypeNames_Ace {
      get {
        return ResourceManager.GetString("TypeNames Ace", resourceCulture);
      }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;&gt;
    ///&lt;Database&gt;{inner-content}
    ///&lt;/Database&gt;.
    /// </summary>
    internal static string Xml_Database {
      get {
        return ResourceManager.GetString("Xml Database", resourceCulture);
      }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;&gt;
    ///&lt;DatabaseCollection&gt;{inner-content}
    ///&lt;/DatabaseCollection&gt;.
    /// </summary>
    internal static string Xml_DatabaseCollection {
      get {
        return ResourceManager.GetString("Xml DatabaseCollection", resourceCulture);
      }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to .
    /// </summary>
    internal static string Xml_Field {
      get {
        return ResourceManager.GetString("Xml Field", resourceCulture);
      }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to 
    ///	&lt;Table Name=&quot;&quot;%TABLE_NAME%&quot;&quot; PrimaryKey=&quot;&quot;%PKUNKNOWN%&quot;&quot;&gt;{inner-content}
    ///	&lt;/Table&gt;.
    /// </summary>
    internal static string Xml_Table {
      get {
        return ResourceManager.GetString("Xml Table", resourceCulture);
      }
    }
  }
}
