//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeneratorTool {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GeneratorTool.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Markdown XHTML File, Shows the content in the navigation window..
        /// </summary>
        internal static string Cmd_BrowserNavigation {
            get {
                return ResourceManager.GetString("Cmd_BrowserNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear the list of download items..
        /// </summary>
        internal static string Cmd_ClearList {
            get {
                return ResourceManager.GetString("Cmd_ClearList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy-MM-dd HH:mm:ss.FFFFF.
        /// </summary>
        internal static string DateFormatDownloader {
            get {
                return ResourceManager.GetString("DateFormatDownloader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c:/users/oio/desktop/dl_{0}.file.
        /// </summary>
        internal static string File_DefaultDownload {
            get {
                return ResourceManager.GetString("File_DefaultDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyyMMdd-HHmmss.
        /// </summary>
        internal static string File_DefaultTimeStamp {
            get {
                return ResourceManager.GetString("File_DefaultTimeStamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash Video|*.flv|MPEG 4 Video|*.mp4|All Files|*.
        /// </summary>
        internal static string FileDialog_MovieTarget {
            get {
                return ResourceManager.GetString("FileDialog_MovieTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text File (*.txt)|*.txt|Text File (*.text)|*.text|All Files|*.
        /// </summary>
        internal static string FileDialog_TextFile {
            get {
                return ResourceManager.GetString("FileDialog_TextFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error creating the Application-Setings Directory..
        /// </summary>
        internal static string MsgErrorCreatingAppSettingsDirectory {
            get {
                return ResourceManager.GetString("MsgErrorCreatingAppSettingsDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error getting the url..
        /// </summary>
        internal static string MsgGetLineFromText {
            get {
                return ResourceManager.GetString("MsgGetLineFromText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your parser.
        /// </summary>
        internal static string MsgGetLineFromText_Caption {
            get {
                return ResourceManager.GetString("MsgGetLineFromText_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The url specified did not exist.
        ///Please correct the matter and try again.
        ///	OK to throw (see) exception
        ///	CANCEL to ignore exception..
        /// </summary>
        internal static string MsgLoadVeetleContent {
            get {
                return ResourceManager.GetString("MsgLoadVeetleContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception.
        /// </summary>
        internal static string MsgLoadVeetleContent_Caption {
            get {
                return ResourceManager.GetString("MsgLoadVeetleContent_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing was found.
        /// </summary>
        internal static string MsgNothingFound {
            get {
                return ResourceManager.GetString("MsgNothingFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This platform is not supported..
        /// </summary>
        internal static string MsgPlatformNotSupported {
            get {
                return ResourceManager.GetString("MsgPlatformNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception.
        /// </summary>
        internal static string MsgPlatformNotSupported_Caption {
            get {
                return ResourceManager.GetString("MsgPlatformNotSupported_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error in your expression..
        /// </summary>
        internal static string MsgRegexError {
            get {
                return ResourceManager.GetString("MsgRegexError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ;(.
        /// </summary>
        internal static string MsgRegexError_Caption {
            get {
                return ResourceManager.GetString("MsgRegexError_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to newdb.db.
        /// </summary>
        internal static string SQLite_Database {
            get {
                return ResourceManager.GetString("SQLite_Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///	DROP TABLE IF EXISTS [targets];
        ///	CREATE TABLE [targets] (
        ///	
        ///	/* @rem so.addVariable(&apos;config&apos;, &apos;/xml/index?id=1105895-277588-26-0-600&apos;) (ptube) */
        ///	[ID]			INTEGER PRIMARY KEY AUTOINCREMENT,
        ///	/* the name of the task */
        ///	[Name]			VARCHAR,
        ///	/* the name of the task */
        ///	[MimeType]		VARCHAR,
        ///	/* the uri being loaded */
        ///	[Uri]			VARCHAR,
        ///	/* POST|GET */
        ///	[UriType]		VARCHAR DEFAULT &apos;GET&apos;,
        ///	/* P=PRIMARY|CHILD=NULL */
        ///	[TypeName]		VARCHAR,
        ///	/* html|xml */
        ///	[Format]		VARCHAR,
        ///	/* a description of th [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SQLite_QueryCreateTargets {
            get {
                return ResourceManager.GetString("SQLite_QueryCreateTargets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select * from [targets].
        /// </summary>
        internal static string SQLite_QueryTarget {
            get {
                return ResourceManager.GetString("SQLite_QueryTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update [targets] set
        ///	[Name]=@name,
        ///	[Uri]=@uri,
        ///	[UriType]=@uritype,
        ///	[MimeType]=@mimetype,
        ///	[TypeName]=@typename,
        ///	[Format]=@format,
        ///	[Description]=@description,
        ///	[NextTarget]=@ntarget,
        ///	[FRegExp]=@regex,
        ///	[Action]=@action,
        ///	[ResultFilter]=@filter,
        ///	[OffsetStart]=@offsetstart,
        ///	[OffsetEnd]=@offsetend,
        ///	[Value]=@value
        ///where [id]=@xid;.
        /// </summary>
        internal static string SQLite_QueryTargetUpdate {
            get {
                return ResourceManager.GetString("SQLite_QueryTargetUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to f:/dev/bin/sqlite3/.
        /// </summary>
        internal static string SQLite_StartPath {
            get {
                return ResourceManager.GetString("SQLite_StartPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;HTML&gt;&lt;body&gt;&lt;H2&gt;Clearing Content…&lt;/H2&gt;&lt;/body&gt;&lt;/HTML&gt;.
        /// </summary>
        internal static string WebBrowser_DocumentTemplate {
            get {
                return ResourceManager.GetString("WebBrowser_DocumentTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Utility Application.
        /// </summary>
        internal static string Window_Title {
            get {
                return ResourceManager.GetString("Window_Title", resourceCulture);
            }
        }
    }
}
